### ISSUE TITLE
Collectd cookbook creates duplicate startup files/instances

### ISSUE THREAD

**Issue by jkugler** [bloomberg/collectd-cookbook#3]
This was originally filed under https://github.com/poise/poise-service/issues/20 and closed.

What it comes down to is this: the collectd cookbook installs system packages, and those system packages have an SysV init file included, which is also started (as is the usual on Debian/Ubuntu systems). Then the collectd cookbook calls Poise, which creates an Upstart config file, and starts that one as well. This leaves two instances of collectd running. The author of poise-service says it's not within the scope of that package to determine if there are other init scripts. Does the collectd cookbook need to test for the presence of other init scripts before it calls poise?

Not 100% sure what the solution is here, but having to manually disable one of the scripts makes the cookbook somewhat frustrating to work with. Other than that, it's helped me a lot! :)

**Comment by johnbellone** [comment]
Ah, so it sounds like we're going to need to remove the old files.

**Comment by jkugler** [comment]
I'm trying to stop/disable the /etc/init.d/ version, but it doesn't seem to be working.  If you're using the system package, which come with their own init files, is there even a reason to use poise-service, which seems to be designed for the case where a service does not come with its own init file.

**Comment by sh9189** [comment]
We need to disable/stop the collectd service that comes with debian package similar to how we do it in the redis cookbook (https://github.com/bloomberg/redis-cookbook/blob/master/libraries/redis_instance.rb#L133-L137)

**Comment by jkugler** [comment]
Odd. After the collectd_service resource call, I have this:

```
service 'collectd' do
  action [ :stop, :disable ]
end
```

But after the node finishes converging, the collectd instance started by /etc/init.d/ is still running.

**Comment by jkugler** [comment]
Hmm...seems `action [ :disable] is disabling the new upstart version, and not the /etc/init.d version. Not the desired outcome. Hmm...

**Comment by johnbellone** [comment]
We're investigating this in #4.
